#! /usr/bin/python

import xml.etree.ElementTree as ET
import tkinter as tk
from tkinter import filedialog
import re, csv
from datetime import timedelta, datetime
 
tkroot = tk.Tk()
tkroot.withdraw()
file = filedialog.askopenfilename()
 
tree = ET.parse(file)
root = tree.getroot()
xmlstr = ET.tostring(root, encoding='utf8', method='xml')
 
ln = re.findall(r'<LineNumber>(\d*)</LineNumber>', (str(xmlstr)))
 
inv = re.findall(r'<InvoiceNumber>(........)', (str(xmlstr)))
 
pnol = re.findall(r'<PartNumberOrdered>([^<]+)</PartNumberOrdered>', (str(xmlstr)))
 
pnsl = re.findall(r'<PartNumberSupplied>([^<]+)</PartNumberSupplied>', (str(xmlstr)))

qtys = re.findall(r'<QuantitySent>(\d*)</QuantitySent>', (str(xmlstr)))

price = re.findall(r'<UnitPrice>([^<]+)</UnitPrice>', (str(xmlstr)))

orderref = re.findall(r'<CustomerOrderRef>(\d*)</CustomerOrderRef>', (str(xmlstr)))

partdiff = [i for i, j in zip(pnol, pnsl) if i != j]
if not partdiff:
    print("All parts match original order.")
else: print("Parts different from original order:"+(str(partdiff)))

csvRows = []
n = 0
while n < len(ln):
    partsup = pnsl[n]
    qty = qtys[n]
    prc = price[n]
    po = orderref[n]
    date = (datetime.now() + timedelta(days=7)).strftime("%Y%m%d")
    row = (inv,partsup,qty,prc,date)
    csvRows.append(row)
    n = n+1

outputfile = open('test.csv', 'w', newline='')
outputwriter = csv.writer(outputfile)
for row in csvRows:
    outputwriter.writerow(row)
outputfile.close()
